python RunFile.py --model MountainCar --rl --scale_sphere 0
python RunFile.py --model MountainCar --rl --scale_sphere 0.25
python RunFile.py --model MountainCar --rl --scale_sphere 0.5
python RunFile.py --model MountainCar --rl --scale_sphere 0.75
python RunFile.py --model MountainCar --rl --scale_sphere 1
python RunFile.py --model MountainCar --rl --scale_sphere 1.25
python RunFile.py --model MountainCar --rl --scale_sphere 1.5
python RunFile.py --model MountainCar --rl --scale_sphere 1.75
python RunFile.py --model MountainCar --rl --scale_sphere 2